### ISSUE TITLE
语法高亮问题 WARN: Could not find the language 'css', did you forget to load/include a language module?

### ISSUE THREAD

**Issue by Mcayear** [EAimTY/materiality-typecho-theme#15]
> [前往现场](https://vusv.cn/p/28.html)

css与js都已按照[要求](https://github.com/EAimTY/materiality-typecho-theme#%E9%85%8D%E7%BD%AE%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE)替换为[highlightjs.org](https://highlightjs.org/download/)下载的内容

![屏幕截图(174)](https://user-images.githubusercontent.com/48203962/173167242-e0eab7d3-dde2-481e-9a09-41445d62df66.png)

**Comment by EAimTY** [comment]
你的主题基于的 materiality-typecho-theme 版本不是最新的，而且替换 highlight.js 的版本也不是最新的
