### ISSUE TITLE
提几个改进建议

### ISSUE THREAD

**Issue by PiktCai** [EAimTY/materiality-typecho-theme#2]
首先，感谢作者为我们带来这么棒的主题，说实话我真的超喜欢！
在这两天的使用中，我总结了几条，希望作者能添加/改进：
1.在主页中，继续阅读按钮于文章的间隔过大，导致空间的浪费，希望能改进；
2.希望能像[manyang901/material](https://github.com/manyang901/material)一样能拥有首页的两个欢迎图，以及每篇文章的无插件统计访客
3.希望能让首页显示文章的略缩图，但最好能够自定义。
再次感谢作者的付出与努力，希望能采纳我的意见。

**Comment by EAimTY** [comment]
谢谢您的反馈！

首先是继续阅读按钮与文章内容之间的间隔过大的问题，这是因为Typecho会自动把在编辑文章时设置的“内容从何处开始不在文章列表中显示”，也就是`<!--more-->`标识转换成
`<p class="more"><a href="文章链接" title="文章标题"></a></p>`
的格式（这个链接不会显示出来，只会占一空行），导致在`mdui-card-content`与`mdui-card-actions`两个div之间被多插入一空行。
解决方法暂时还没有找到，把`<!--more-->`标识之前的内容留多一些，并且在文章的每一段之间多插入一些空行，就能显得继续阅读按钮与文章内容之间的间隔不那么大了。当然这只是暂时的解决方法，我之后会想办法改进的。

添加首页欢迎图与文章缩略图已经在开发计划中了，但是最近比较忙，所以可能需要再等一段时间才会放出新版本。

至于无插件统计访客功能，我认为这应该是一个“食之无味弃之可惜”的鸡肋功能，即使加入了这项功能，实用性也不会很高，还会使主题更加臃肿。毕竟这只是一个主题。如果需要此类功能，建议去装一个Access之类的功能齐全的独立统计插件吧。

**Comment by PiktCai** [comment]
＠EAimTY 抱歉，我可能没说清楚，我的意思是能够在主页里每篇文章的卡片中显示已查看过该文章的人数，而并非是整个网站的访客统计，样式我认为同样可以参照[manyang901/material](https://github.com/manyang901/material)
