### ISSUE TITLE
请教一下如何适应移动端

### ISSUE THREAD

**Issue by ZigZagK** [EAimTY/materiality-typecho-theme#3]
我也在用MDUI写主题QwQ，但是我发现我的主题无法适应移动端。
请问MDUI自带了这个功能吗？我现在不知道是我有地方没注意还是MDUI并没有这种功能，求教QAQ。

**Comment by EAimTY** [comment]
MDUI是支持自适应的，可能是您的嵌套结构没有写好，建议您找一个使用MDUI的网页借鉴一下代码结构。

**Comment by ZigZagK** [comment]
> MDUI是支持自适应的，可能是您的嵌套结构没有写好，建议您找一个使用MDUI的网页借鉴一下代码结构。

好的，谢谢QwQ。
