### ISSUE TITLE
 输入域 mdui-textfield-not-empty 问题

### ISSUE THREAD

**Issue by ImYuanY** [EAimTY/materiality-typecho-theme#4]
如果浏览器对文本框等输入域自动添充了内容，输入域的标签样式并不会自动修改。也就是`<label />`标签的上层`<div />`并不会自动加入 `mdui-textfield-not-empty ` 这个 class name，造成标签文字与输入域内容重叠，当鼠标点击或光标焦点进入后才会更正样式。

**Comment by EAimTY** [comment]
这个应该MDUI的bug，我已经将本项目中的MDUI更新到了最新版本，最新版本不再存在这个问题。
