### ISSUE TITLE
更换主题颜色导致的无限加载

### ISSUE THREAD

**Issue by voipsy** [EAimTY/materiality-typecho-theme#8]
在更换 主题强调色 后，在主界面不能正常显示颜色，并且有加载圈旋转。
`Notice: Undefined variable: parent in /data/wwwroot/****/usr/themes/materiality-typecho-theme/functions.php on line 60`

**Comment by voipsy** [comment]
补充一下，如果切换到暗色主题，再刷新，则可以暂时解决该问题。
同时页脚显示 
`Notice
: Undefined index: dark in
/data/wwwroot/****/usr/themes/materiality-typecho-theme/footer.php
on line
3
`

**Comment by EAimTY** [comment]
抱歉，我未能复现你所提到的“不能正常显示颜色”。你所提到的两条 Notice 是关于未初始化变量与数组的，理论上讲不会影响到颜色的显示与变更。我在 c323c9dd1b3e24e43b56a9c9cb8eb162719b9187 中尝试解决了这个问题，请更新主题试试。如果颜色显示还有问题，希望你能提供更详细的信息。

另外，建议修改在生产环境下 PHP 的 error_reporting，暴露 Notice 和 Warning 可能会导致一些安全问题。

**Comment by voipsy** [comment]
抱歉，这么晚才回覆！
尝试了你的建议，惊奇的发现：
在新的版本中似乎已经解决了该问题，感谢！
