### ISSUE TITLE
页码选择器CSS样式错误

### ISSUE THREAD

**Issue by huhaorui** [EAimTY/materiality-typecho-theme#9]
页码选择器的UI显示存在问题
![image](https://user-images.githubusercontent.com/43870434/107149897-2e6f7780-6996-11eb-8f9d-d480fab2cc4f.png)
可以参见[我的网站](https://www.huhaorui.com/category/%25e4%25bb%25a3%25e7%25a0%2581%25e4%25bd%25bf%25e4%25ba%25ba%25e5%25bf%25ab%25e4%25b9%2590/)

**Comment by EAimTY** [comment]
Typecho 对跳页按钮的自定义支持实在有限，所以目前我是通过页面加载时执行 js 来构造跳页按钮的。请问你是否自行修改过 js 代码或跳页按钮的 html？修改时要确保 pagenav 函数在页面加载时执行，并且保留跳页按钮的 id 属性和 class。
我之后会把跳页按钮的构造改成借助 ob 处理，不再依赖 js

**Comment by huhaorui** [comment]
我使用了git clone的方法获取代码，除了添加代码高亮的js之外，没有进行额外的操作。该bug在一些其他人的博客上也可以复现，例如 https://hkr233.top/index.php/2020/11/



---原始邮件---
发件人: "EAimTY"<notifications@github.com&gt;
发送时间: 2021年2月8日(周一) 下午4:21
收件人: "EAimTY/materiality-typecho-theme"<materiality-typecho-theme@noreply.github.com&gt;;
抄送: "huhaorui"<i@huhaorui.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [EAimTY/materiality-typecho-theme] 页码选择器CSS样式错误 (#9)




 
Typecho 对跳页按钮的自定义支持实在有限，所以目前我是通过页面加载时执行 js 来构造跳页按钮的。请问你是否自行修改过 js 代码或跳页按钮的 html？修改时要确保 pagenav 函数在页面加载时执行，并且保留跳页按钮的 id 属性和 class。
 我之后会把跳页按钮的构造改成借助 ob 处理，不再依赖 js

**Comment by EAimTY** [comment]
抱歉，是我大意了，这的确是归档页面的代码笔误。
这个 bug 的临时解决方案是将`archive.php`中第 44 行的`id="page-nav"`改为`id="pagenav"`，我也会尽快修复的

**Comment by EAimTY** [comment]
已经在 4177d01a03397b57ff138d9946bf6c28d4c703cb 中修复了这个问题，请更新试一试

**Comment by huhaorui** [comment]
原先的问题解决了，但是产生了新的问题，如图



---原始邮件---
发件人: "EAimTY"<notifications@github.com&gt;
发送时间: 2021年2月8日(周一) 下午5:41
收件人: "EAimTY/materiality-typecho-theme"<materiality-typecho-theme@noreply.github.com&gt;;
抄送: "huhaorui"<i@huhaorui.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [EAimTY/materiality-typecho-theme] 页码选择器CSS样式错误 (#9)




 
已经在 4177d01 中修复了这个问题，请更新试一试

**Comment by EAimTY** [comment]
已在 114015ac24dc82d3383f04da43c0b6d7d9b7f51b 中修复

**Comment by huhaorui** [comment]
问题已解决，感谢！
